### ISSUE TITLE
Error: Cannot find module 'graphql/language/printer'

### ISSUE THREAD

**Issue by 2ndalpha** [Qminder/javascript-api#452]
Stacktrace:
> Error: Cannot find module 'graphql/language/printer'
> Require stack:
> - /Users/siim/git/qminder-api-test/node_modules/qminder-api/build/services/GraphQLService.js
> - /Users/siim/git/qminder-api-test/node_modules/qminder-api/build/qminder-api.js

Minimum example is here: https://github.com/2ndalpha/qminder-api-test
Clone the repo and run
```bash
yarn
yarn ts-node src/minimum.ts
```

**Comment by KarlMae** [comment]
Error happens because of missing peerDependencies in the consumer.

Research best practices how to request deps from consumer - implement them, document them, add them to README if necessary.
