### ISSUE TITLE
navigator.userAgent.match throws an exception in React Native

### ISSUE THREAD

**Issue by filiphosko** [Qminder/javascript-api#97]
Since React Native is an environment per se (and not a browser), [this line](https://github.com/Qminder/javascript-api/blob/master/src/qminder-api.js#L720) throws an exception and Qminder events won't get registered. You should first be checking if navigator.userAgent is not undefined and then do the matching. I hope this will get fixed, I can submit a PR for it but I don't know if you are accepting PRs.

In the meantime if anybody stumbles upon this and wants a quick hackfix, just put something like this in your app: ```global.navigator.userAgent = 'ReactNative';```

**Comment by boxmein** [comment]
Hi! 

Thanks for reporting this to us. I've pushed out a preliminary fix, which I tested on a React Native app template.

Can you test this and let me know if it works for you?

**Comment by filiphosko** [comment]
I'll check it and let you know.
